# Generated by Django 4.1.3 on 2023-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobies',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg_four',
            field=models.ImageField(default='blank-img.png', upload_to='main_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg_one',
            field=models.ImageField(default='blank-img.png', upload_to='main_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg_three',
            field=models.ImageField(default='blank-img.png', upload_to='main_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg_two',
            field=models.ImageField(default='blank-img.png', upload_to='main_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
