# Generated by Django 4.1.3 on 2023-07-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg_four',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg_one',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg_three',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileimg_two',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='religion',
        ),
    ]
